# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  projectNameWebApi: 'App.WebApi'
  projectNameWebUiAdmin: 'App.WebUi.Admin'
  serviceConnection: 'Dev service connection quizapp'

# TODO: Split this into sensible stages
stages:
- stage: dev
  displayName: Dev
  variables:
    buildConfiguration: 'Release'
  jobs:
  - job: deploy
    displayName: Deploy
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 8.x'
      inputs:
        packageType: sdk
        version: '8.x'
    - task: AzureKeyVault@2
      displayName: 'Get keyvault values'
      inputs:
        azureSubscription: $(serviceConnection)
        KeyVaultName: 'ct-dev-kv'
        SecretsFilter: 'ConnectionStrings--DefaultConnection'
        RunAsPreJob: true

    # TODO: Remove
    - script: |
        echo "Secret starts with: ${CONNECTION_STRING:0:5}*******"
      displayName: 'Echo Partial Secret (Masked)'
      env:
        CONNECTION_STRING: $(ConnectionStrings--DefaultConnection)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: 'Build $(projectNameWebApi) - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/$(projectNameWebApi).csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish $(projectNameWebApi) - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/$(projectNameWebApi).csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - script: |
        dotnet tool install --global dotnet-ef
      displayName: 'Install dotnet-ef CLI'

    - task: DotNetCoreCLI@2
      displayName: 'Create Database EF Migration Bundle'
      inputs:
        command: 'custom'
        custom: 'ef'
        arguments: 'migrations bundle --self-contained -r linux-x64 --output efbundle'
        workingDirectory: '$(Build.SourcesDirectory)/App.DatabaseSource'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Database EF Migration Bundle'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/App.DatabaseSource/efbundle'
        ArtifactName: 'MigrationBundle'

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'MigrationBundle'
        targetPath: '$(Pipeline.Workspace)/MigrationBundle'
      displayName: 'Download Database EF Migration Bundle'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(Pipeline.Workspace)/MigrationBundle
          chmod +x efbundle
          ./efbundle --connection "$(ConnectionStrings--DefaultConnection)"

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy $(projectNameWebApi)'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(serviceConnection)
        appType: 'webApp'
        WebAppName: 'ct-dev-quizapp-api'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)/**/$(projectNameWebApi).zip'